CREATE TABLE CONTINGENCIA_CONTRATO_RESPUESTA (
    -- Uso de Identity Columns (Nativo desde 12c)
    RESPUESTA_ID           NUMBER(38) GENERATED by default on null AS IDENTITY,
    CONTINGENCIA_ID        NUMBER(38) NOT NULL,
    FECHA_REGISTRO         TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    DESCRIPCION_ACCION     CLOB NOT NULL,
    USUARIO_CONTRATISTA_ID NUMBER(38) NOT NULL,
   
    
    CONSTRAINT PK_CONTING_RESP PRIMARY KEY (RESPUESTA_ID),
    CONSTRAINT FK_RESP_CONTING FOREIGN KEY (CONTINGENCIA_ID) 
        REFERENCES CONTINGENCIA_CONTRATO(CONTINGENCIA_ID)
);

-- REGLA DE ORO ORACLE: Indexar SIEMPRE las llaves foráneas para evitar Table Locks
CREATE INDEX IX_RESP_CONTING ON CONTINGENCIA_CONTRATO_RESPUESTA(CONTINGENCIA_ID);

CREATE OR REPLACE PACKAGE PKG_GESTION_CONTINGENCIAS3 AS

  -- (Se mantiene) Registra la contingencia inicial
  PROCEDURE PRC_REGISTRAR_CONTINGENCIA (
    p_contrato_id             IN NUMBER,
    p_descripcion_observacion IN VARCHAR2,
    p_dias_subsanacion        IN NUMBER,
    p_usuario_registra_id     IN NUMBER,
    p_planilla_id             IN NUMBER DEFAULT NULL
  );

  -- (NUEVO) El contratista registra su acción de subsanación
  PROCEDURE PRC_REGISTRAR_RESPUESTA (
    p_contingencia_id        IN NUMBER,
    p_descripcion_accion     IN CLOB,
    p_usuario_contratista_id IN NUMBER,
    o_respuesta_id           OUT NUMBER -- Retorna el ID para adjuntar la evidencia luego
  );

  -- (MODIFICADO) El fiscalizador evalúa la respuesta y aprueba o rechaza la subsanación
  PROCEDURE PRC_EVALUAR_CONTINGENCIA (
    p_contingencia_id     IN NUMBER,
    p_usuario_fiscaliza   IN NUMBER,
    p_es_aprobada         IN VARCHAR2, -- 'S' = Aprobada (Subsanada), 'N' = Rechazada
    p_motivo_rechazo      IN VARCHAR2 DEFAULT NULL
  );

  -- (Se mantiene) Job nocturno
  PROCEDURE PRC_VERIFICAR_VENCIMIENTOS;

END PKG_GESTION_CONTINGENCIAS3;
/  

CREATE OR REPLACE PACKAGE BODY PKG_GESTION_CONTINGENCIAS3 AS

  -- ... (PRC_REGISTRAR_CONTINGENCIA se mantiene igual al anterior) ...

  -- =========================================================================
  -- PROCEDIMIENTO: PRC_REGISTRAR_RESPUESTA (PERFIL: CONTRATISTA)
  -- =========================================================================
  PROCEDURE PRC_REGISTRAR_RESPUESTA (
    p_contingencia_id        IN NUMBER,
    p_descripcion_accion     IN CLOB,
    p_usuario_contratista_id IN NUMBER,
    o_respuesta_id           OUT NUMBER
  ) IS
    v_estado_actual NUMBER;
  BEGIN
    -- 1. Validar que la contingencia siga abierta
    SELECT ESTADO_CONTINGENCIA_ID INTO v_estado_actual
    FROM CONTINGENCIA_CONTRATO
    WHERE CONTINGENCIA_ID = p_contingencia_id;
    
    IF v_estado_actual <> 81 /* ABIERTA */ THEN
       RAISE_APPLICATION_ERROR(-20104, 'No puede responder a una contingencia que ya está cerrada o incumplida.');
    END IF;

    -- 2. Insertar la respuesta y recuperar el ID generado automáticamente
    -- Asumiendo que RESPUESTA_ID es un GENERATED ALWAYS AS IDENTITY
    INSERT INTO CONTINGENCIA_CONTRATO_RESPUESTA (
      CONTINGENCIA_ID,
      FECHA_REGISTRO,
      DESCRIPCION_ACCION,
      USUARIO_CONTRATISTA_ID
    ) VALUES (
      p_contingencia_id,
      SYSTIMESTAMP,
      p_descripcion_accion,
      p_usuario_contratista_id
    ) RETURNING RESPUESTA_ID INTO o_respuesta_id;
    
    -- Nota: Al retornar 'o_respuesta_id', tu aplicación (APEX, Java, C#, etc.) 
    -- puede tomar este valor inmediatamente para insertar en CONTINGENCIA_CONTRATO_EVIDENCIA.

  END PRC_REGISTRAR_RESPUESTA;

  -- =========================================================================
  -- PROCEDIMIENTO: PRC_EVALUAR_CONTINGENCIA (PERFIL: FISCALIZADOR)
  -- =========================================================================
  PROCEDURE PRC_EVALUAR_CONTINGENCIA (
    p_contingencia_id     IN NUMBER,
    p_usuario_fiscaliza   IN NUMBER,
    p_es_aprobada         IN VARCHAR2, 
    p_motivo_rechazo      IN VARCHAR2 DEFAULT NULL
  ) IS
    v_contrato_id CONTRATO.CONTRATO_ID%TYPE;
    v_planilla_id CONTINGENCIA_CONTRATO.PLANILLA_ID%TYPE;
    v_estado      CONTINGENCIA_CONTRATO.ESTADO_CONTINGENCIA_ID%TYPE;
  BEGIN
    -- Obtener datos de la contingencia
    SELECT CONTRATO_ID, PLANILLA_ID, ESTADO_CONTINGENCIA_ID 
    INTO v_contrato_id, v_planilla_id, v_estado
    FROM CONTINGENCIA_CONTRATO 
    WHERE CONTINGENCIA_ID = p_contingencia_id;

    IF v_estado <> 81 /* 'ABIERTA' */ THEN
      RAISE_APPLICATION_ERROR(-20102, 'La contingencia no se encuentra en estado de evaluación.');
    END IF;

    IF p_es_aprobada = 'S' THEN
      -- APROBADA: Subsanar la contingencia
      UPDATE CONTINGENCIA_CONTRATO
      SET ESTADO_CONTINGENCIA_ID = 82, /* 'SUBSANADA' */
          FECHA_RESOLUCION = SYSDATE
      WHERE CONTINGENCIA_ID = p_contingencia_id;

      -- Liberar la Planilla vinculada si existe
      IF v_planilla_id IS NOT NULL THEN
         UPDATE PLANILLA_CONTRACTUAL
         SET ESTADO_ID = 91, -- HABILITADA
             OBSERVACION_TECNICA = TO_CLOB('Contingencia subsanada aprobada por Fiscalización.')
         WHERE PLANILLA_ID = v_planilla_id;
      END IF;

      -- Actualizar Contrato
      UPDATE CONTRATO
      SET COMENTARIO = 'Contingencia solventada exitosamente.'
      WHERE CONTRATO_ID = v_contrato_id;

    ELSIF p_es_aprobada = 'N' THEN
      -- RECHAZADA: La contingencia sigue abierta, pero notificamos el rechazo
      -- (Opcionalmente podrías cambiar a estado 'INCUMPLIDA' si es grave)
      UPDATE CONTRATO
      SET COMENTARIO = 'Fiscalización RECHAZÓ la respuesta de subsanación. Motivo: ' || p_motivo_rechazo
      WHERE CONTRATO_ID = v_contrato_id;
      
      -- Si existe planilla, reforzamos que sigue retenida
      IF v_planilla_id IS NOT NULL THEN
         UPDATE PLANILLA_CONTRACTUAL
         SET OBSERVACION_TECNICA = TO_CLOB('Respuesta rechazada. La planilla continúa retenida.')
         WHERE PLANILLA_ID = v_planilla_id;
      END IF;
      
    ELSE
       RAISE_APPLICATION_ERROR(-20105, 'El parámetro de aprobación debe ser S o N.');
    END IF;

  END PRC_EVALUAR_CONTINGENCIA;

  -- ... (PRC_VERIFICAR_VENCIMIENTOS se mantiene igual al anterior) ...

END PKG_GESTION_CONTINGENCIAS3;
/